import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import { AuroraText } from "@/components/magicui/aurora-text";
import { Dock, DockIcon } from "@/components/magicui/dock";
import { FaGithub, FaLinkedin } from "react-icons/fa";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Eleoterio - Web Developer Portfolio",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`antialiased text-white bg-black ${inter.variable}`}>
        <header className="fixed left-10 top-10">
          <p>
            <AuroraText className="font-bold text-3xl">M.</AuroraText> <br />{" "}
            <span className="font-thin text-xl">Eleotério</span>
          </p>
        </header>
        {children}
        <div className="fixed w-full bottom-10 mx-auto">
          <Dock iconMagnification={60} iconDistance={100} direction="middle">
            <DockIcon>
              <Link href="https://github.com/m-eleoterio" target="_blank">
                <FaGithub />
              </Link>
            </DockIcon>
            <DockIcon>
              <Link
                href="https://www.linkedin.com/in/miguel-eleoterio-vieira-206112250/"
                target="_blank"
              >
                <FaLinkedin />
              </Link>
            </DockIcon>
          </Dock>
        </div>
      </body>
    </html>
  );
}
